### ISSUE TITLE
ci_script broke ceph playbook

### ISSUE THREAD

**Issue by fultonj** [openstack-k8s-operators/ci-framework#531]
After [1] merged I've been unable to use the ceph playbook in a standalone context as documented in the `cifmw_cephadm`
role readme [2]. Instead I get:
```
  Permission denied: '/root/ci-framework-data/artifacts'
```
I can't even override it easily by passing something like:
```
  -e cifmw_cephadm_basedir=/tmp
```
I tried adding a pre_task to ensure `cifmw_cephadm_basedir` (and `cifmw_cephadm_basedir/artifacts`) exists but this lead my down a rabbit hole of having to create other directories for it until it mysteriously failed.
```
TASK [cifmw_cephadm : Run cephadm bootstrap output_dir={{ cifmw_cephadm_basedir }}/artifacts, script={{ cifmw_cephadm_bin }} \
{% if not cifmw_cephadm_default_container %}--image {{ cifmw_cephadm_container_ns + '/' + cifmw_cephadm_container_image + ':' + cifmw_cephadm_container_tag|string }} \{% endif %}
bootstrap \
--skip-firewalld \
--skip-prepare-host \
--ssh-private-key /home/{{ cifmw_cephadm_ssh_user }}/.ssh/id_rsa \
--ssh-public-key /home/{{ cifmw_cephadm_ssh_user }}/.ssh/id_rsa.pub \
--ssh-user {{ cifmw_cephadm_ssh_user }} \
--allow-fqdn-hostname \
--output-keyring {{ cifmw_cephadm_admin_keyring }} \
--output-config {{ cifmw_cephadm_conf }} \
--fsid {{ cifmw_cephadm_fsid }} \
{% if cifmw_cephadm_registry_url|length > 0 %}--registry-url {{ cifmw_cephadm_registry_url }} \{% endif %}
{% if cifmw_cephadm_registry_username|length > 0 %}--registry-username {{ cifmw_cephadm_registry_username }} \{% endif %}
{% if cifmw_cephadm_registry_password|length > 0 %}--registry-password {{ cifmw_cephadm_registry_password }} \{% endif %}
{% if cifmw_cephadm_spec_on_bootstrap %}--apply-spec {{ cifmw_cephadm_spec }} \{% endif %}
{% if cifmw_cephadm_assimilate_conf_stat.stat.exists %}--config {{ cifmw_cephadm_assimilate_conf }} \{% endif %}
{% if cifmw_cephadm_single_host_defaults %}--single-host-defaults \{% endif %}
--skip-monitoring-stack --skip-dashboard \
{% if cifmw_cephadm_extra_args|length > 0 %}{{ cifmw_cephadm_extra_args }} \{% endif %}
--mon-ip {{ cifmw_cephadm_first_mon_ip }}
] ***
task path: /home/fultonj/ci-framework/ci_framework/roles/cifmw_cephadm/tasks/bootstrap.yml:48
The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ansible/executor/task_executor.py", line 147, in run
    res = self._execute()
  File "/usr/lib/python3.6/site-packages/ansible/executor/task_executor.py", line 665, in _execute
    result = self._handler.run(task_vars=variables)
  File "/home/fultonj/ci-framework/ci_framework/plugins/action/ci_script.py", line 148, in run
    t_name = re.sub(r'([^\x00-\x7F]|\s)+', '_', self._task._name).lower()
  File "/usr/lib64/python3.6/re.py", line 191, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object
fatal: [192.168.122.100]: FAILED! => {
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}
```

[1] https://github.com/openstack-k8s-operators/ci-framework/commit/0df6fa4cef78a8147405e40d3ebaa9672040846b
[2] https://github.com/openstack-k8s-operators/ci-framework/blob/main/ci_framework/roles/cifmw_cephadm/README.md#examples

**Comment by fultonj** [comment]
I read that `ci_script` runs a given script _remotely_ 

All roles in ci-framework which use it [2] are in plays which run either against localhost or the cifmw_target_host [3]. 

That paradigm is different in how the ceph playbook works where it's designed to be run from the localhost but to run the ceph bootstrap command on a remote host. I'm not sure the ceph playbook is a good candidate for CI script action. We have had ceph bootstrapping fine for years without ci_script and using shell in TripleO CI. If we really need something like this, then let's collaborate more closely and get a working version. For now I think we should revert until that point. 

My bad for initially approving the PR initially without testing. I assumed it would be transparent. 

[1] https://github.com/openstack-k8s-operators/ci-framework/blob/main/ci_framework/plugins/action/ci_script.py

[2] 
[fultonj@hamfast roles{fix}]$ grep -R ci_script | awk -F / {'print $1'} | uniq
artifacts
cifmw_cephadm
copy_container
edpm_deploy
edpm_kustomize
edpm_prepare
libvirt_manager
openshift_provisioner_node
os_must_gather
set_openstack_containers
[fultonj@hamfast roles{fix}]$ 

[3]
[fultonj@hamfast playbooks{fix}]$ grep hosts *
01-bootstrap.yml:  hosts: "{{ cifmw_target_host | default('localhost') }}"
02-infra.yml:  hosts: "{{ ('virthosts' in groups) | ternary('virthosts', cifmw_target_host | default('localhost') ) }}"
02-infra.yml:  hosts: "{{ cifmw_target_host | default('localhost') }}"
03-build-packages.yml:  hosts: "{{ cifmw_target_host | default('localhost') }}"
04-build-containers.yml:  hosts: "{{ cifmw_target_host | default('localhost') }}"
05-build-operators.yml:  hosts: "{{ cifmw_target_host | default('localhost') }}"
06-deploy-edpm.yml:  hosts: "{{ cifmw_target_host | default('localhost') }}"
06-deploy-edpm.yml:  hosts: "{{ cifmw_target_host | default('localhost') }}"
07-admin-setup.yml:  hosts: "{{ cifmw_target_host | default('localhost') }}"
08-run-tests.yml:  hosts: "{{ cifmw_target_host | default('localhost') }}"
99-logs.yml:  hosts: "{{ cifmw_target_host | default('localhost') }}"
ceph.yml:  hosts: localhost
ceph.yml:  hosts: edpm
ceph.yml:  hosts: edpm
ceph.yml:  hosts: localhost
ceph.yml:  hosts: edpm[0]
ceph.yml:  hosts: localhost
hooks.yml:  hosts: "{{ cifmw_target_host | default('localhost') }}"
[fultonj@hamfast playbooks{fix}]$

**Comment by fultonj** [comment]
Thanks for merging the revert.
